package com.example.demoS.entity;
// Generated Jun 15, 2022, 11:29:00 AM by Hibernate Tools 3.6.2.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ApplyStatus generated by hbm2java
 */
@Entity
@Table(name = "ApplyStatus")
public class ApplyStatus {

	private long id;
	private String name;
	private String description;
	private Set<Apply> applies = new HashSet<Apply>(0);

	public ApplyStatus() {
	}

	public ApplyStatus(long id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public ApplyStatus(long id, String name, String description, Set<Apply> applies) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.applies = applies;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applyStatus")
	public Set<Apply> getApplies() {
		return this.applies;
	}

	public void setApplies(Set<Apply> applies) {
		this.applies = applies;
	}

}
