package com.example.demoS.entity;
// Generated Jun 15, 2022, 11:29:00 AM by Hibernate Tools 3.6.2.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Apply generated by hbm2java
 */
@Entity
@Table(name = "Apply")
public class Apply {

	private long id;
	private Project project;
	private FreelancerAccount freelancerAccount;
	private ApplyStatus applyStatus;
	private String date;
	private int bid;
	private String createDate;
	private Set<Report> reports = new HashSet<Report>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Apply() {
	}

	public Apply(long id, String date, int bid) {
		this.id = id;
		this.date = date;
		this.bid = bid;
	}

	public Apply(long id, Project project, FreelancerAccount freelancerAccount, ApplyStatus applyStatus, String date,
			int bid, String createDate, Set<Report> reports, Set<Payment> payments) {
		this.id = id;
		this.project = project;
		this.freelancerAccount = freelancerAccount;
		this.applyStatus = applyStatus;
		this.date = date;
		this.bid = bid;
		this.createDate = createDate;
		this.reports = reports;
		this.payments = payments;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectID")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FreelancerID")
	public FreelancerAccount getFreelancerAccount() {
		return this.freelancerAccount;
	}

	public void setFreelancerAccount(FreelancerAccount freelancerAccount) {
		this.freelancerAccount = freelancerAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ApplyStatusID")
	public ApplyStatus getApplyStatus() {
		return this.applyStatus;
	}

	public void setApplyStatus(ApplyStatus applyStatus) {
		this.applyStatus = applyStatus;
	}

	
	@Column(name = "Date", nullable = false, length = 23)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "Bid", nullable = false)
	public int getBid() {
		return this.bid;
	}

	public void setBid(int bid) {
		this.bid = bid;
	}

	
	@Column(name = "CreateDate", length = 10)
	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apply")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apply")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
