package com.example.demoS.entity;
// Generated Jun 15, 2022, 11:29:00 AM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CustomerAccount generated by hbm2java
 */
@Entity
@Table(name = "CustomerAccount")
public class CustomerAccount {

	private long id;
	private UserAccount userAccount;
	private Company company;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Report> reports = new HashSet<Report>(0);

	public CustomerAccount() {
	}

	public CustomerAccount(long id, UserAccount userAccount) {
		this.id = id;
		this.userAccount = userAccount;
	}

	public CustomerAccount(int id, UserAccount userAccount, Company company, Set<Project> projects,
			Set<Report> reports) {
		this.id = id;
		this.userAccount = userAccount;
		this.company = company;
		this.projects = projects;
		this.reports = reports;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CompanyID")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerAccount")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerAccount")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

}
