package com.example.demoS.entity;
// Generated Jun 15, 2022, 11:29:00 AM by Hibernate Tools 3.6.2.Final



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "Payment")
public class Payment  {

	private long id;
	private Apply apply;
	private String date;
	private String paymentMethod;
	private Set<Transactions> transactionses = new HashSet<Transactions>(0);

	public Payment() {
	}

	public Payment(long id, String date, String paymentMethod) {
		this.id = id;
		this.date = date;
		this.paymentMethod = paymentMethod;
	}

	public Payment(long id, Apply apply, String date, String paymentMethod, Set<Transactions> transactionses) {
		this.id = id;
		this.apply = apply;
		this.date = date;
		this.paymentMethod = paymentMethod;
		this.transactionses = transactionses;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ApplyID")
	public Apply getApply() {
		return this.apply;
	}

	public void setApply(Apply apply) {
		this.apply = apply;
	}


	@Column(name = "Date", nullable = false, length = 23)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "PaymentMethod", nullable = false)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payment")
	public Set<Transactions> getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set<Transactions> transactionses) {
		this.transactionses = transactionses;
	}

}
