package com.example.demoS.entity;
// Generated Jun 15, 2022, 11:29:00 AM by Hibernate Tools 3.6.2.Final



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "Report")
public class Report {

	private long id;
	private CustomerAccount customerAccount;
	private Apply apply;
	private FreelancerAccount freelancerAccount;
	private String title;
	private String reportTime;
	private String reportItem;
	private int status;

	public Report() {
	}

	public Report(long id, String title, String reportItem, int status) {
		this.id = id;
		this.title = title;
		this.reportItem = reportItem;
		this.status = status;
	}

	public Report(long id, CustomerAccount customerAccount, Apply apply, FreelancerAccount freelancerAccount,
			String title, String reportTime, String reportItem, int status) {
		this.id = id;
		this.customerAccount = customerAccount;
		this.apply = apply;
		this.freelancerAccount = freelancerAccount;
		this.title = title;
		this.reportTime = reportTime;
		this.reportItem = reportItem;
		this.status = status;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerID")
	public CustomerAccount getCustomerAccount() {
		return this.customerAccount;
	}

	public void setCustomerAccount(CustomerAccount customerAccount) {
		this.customerAccount = customerAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ApplyID")
	public Apply getApply() {
		return this.apply;
	}

	public void setApply(Apply apply) {
		this.apply = apply;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FreelancerID")
	public FreelancerAccount getFreelancerAccount() {
		return this.freelancerAccount;
	}

	public void setFreelancerAccount(FreelancerAccount freelancerAccount) {
		this.freelancerAccount = freelancerAccount;
	}

	@Column(name = "Title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}


	@Column(name = "ReportTime", length = 23)
	public String getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(String reportTime) {
		this.reportTime = reportTime;
	}

	@Column(name = "ReportItem", nullable = false)
	public String getReportItem() {
		return this.reportItem;
	}

	public void setReportItem(String reportItem) {
		this.reportItem = reportItem;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
