package com.example.demoS.entity;
// Generated Jun 15, 2022, 11:29:00 AM by Hibernate Tools 3.6.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Skill generated by hbm2java
 */
@Entity
@Table(name = "Skill")
public class Skill {

	private long id;
	private Tech tech;
	private FreelancerAccount freelancerAccount;

	public Skill() {
	}

	public Skill(long id) {
		this.id = id;
	}

	public Skill(long id, Tech tech, FreelancerAccount freelancerAccount) {
		this.id = id;
		this.tech = tech;
		this.freelancerAccount = freelancerAccount;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TechID")
	public Tech getTech() {
		return this.tech;
	}

	public void setTech(Tech tech) {
		this.tech = tech;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FreelancerID")
	public FreelancerAccount getFreelancerAccount() {
		return this.freelancerAccount;
	}

	public void setFreelancerAccount(FreelancerAccount freelancerAccount) {
		this.freelancerAccount = freelancerAccount;
	}

}
