package com.example.demoS.entity;
// Generated Jun 15, 2022, 11:29:00 AM by Hibernate Tools 3.6.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name = "Transactions")
public class Transactions  {

	private long id;
	private FreelancerAccount freelancerAccount;
	private Payment payment;
	private int amount;

	public Transactions() {
	}

	public Transactions(long id, int amount) {
		this.id = id;
		this.amount = amount;
	}

	public Transactions(long id, FreelancerAccount freelancerAccount, Payment payment, int amount) {
		this.id = id;
		this.freelancerAccount = freelancerAccount;
		this.payment = payment;
		this.amount = amount;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FreelancerID")
	public FreelancerAccount getFreelancerAccount() {
		return this.freelancerAccount;
	}

	public void setFreelancerAccount(FreelancerAccount freelancerAccount) {
		this.freelancerAccount = freelancerAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PaymentID")
	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	@Column(name = "Amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

}
